### ISSUE TITLE
Make parser PHP 8.0 compatible

### ISSUE THREAD

**Issue by peterjaap** [elgentos/parser#7]
I tried to make [masquerade](https://github.com/elgentos/masquerade) PHP 8.0 compatible but ran into the following error;

`PHP Parse error:  syntax error, unexpected token "match" in /data/elgentos/masquerade/vendor/elgentos/parser/src/Parser/Stories/Reader/Complex.php on line 83`

It turns out, `match` (and `Match`) is now a reserved word in PHP 8.0 due to the [match expression RFC](https://wiki.php.net/rfc/match_expression_v2). 

So this class should be renamed; https://github.com/elgentos/parser/blob/master/src/Parser/Rule/Match.php

**Comment by peterjaap** [comment]
Possible new names; `Matches` (as in, "this matches that", not as in plural for `Match`) or `MatchRule` ?

**Comment by janmartenjongerius** [comment]
@peterjaap I've been having this pull request in review for quite a while now: https://github.com/elgentos/parser/pull/6
That basically fixes your issue.

The pull request still needs some love, because our Travis tests no longer work. I suggested to move to GitHub Actions instead, so we can manage GitHub developer access and GitHub CI access in the same place.

That still needs to be done.
